<%@page contentType="text/html" pageEncoding="UTF-8"%><%@taglib prefix="c" uri="jakarta.tags.core"%>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Điều hành phòng khám</title><link rel="stylesheet" href="${pageContext.request.contextPath}/static/css/style.css"></head><body>
<jsp:include page="header.jsp"/><jsp:include page="topnav.jsp"/><main class="page-wrapper workflow-page">
<div class="page-heading"><div><div class="eyebrow">VẬN HÀNH NGOẠI TRÚ</div><h1 class="page-title">Điều hành phòng khám</h1><p class="text-muted">Lịch hẹn → tiếp nhận → hàng đợi → khám → xét nghiệm → hoàn tất</p></div></div>
<c:if test="${not empty workflowFlash}"><div class="alert alert-info"><c:out value="${workflowFlash}"/></div></c:if>
<nav class="module-tabs"><a class="${view=='appointments'?'active':''}" href="?view=appointments">Lịch hẹn</a><a class="${view=='encounters'?'active':''}" href="?view=encounters">Lượt khám & hàng đợi</a><a class="${view=='clinical'?'active':''}" href="?view=clinical">Dị ứng & tiền sử</a><a class="${view=='labs'?'active':''}" href="?view=labs">Chỉ định xét nghiệm</a></nav>

<c:if test="${view=='appointments'}">
 <c:if test="${sessionScope.user.role=='STAFF'||sessionScope.user.role=='ADMIN'}"><section class="card"><div class="card-title">Tạo lịch hẹn</div><form method="post" action="ClinicWorkflow" class="form-grid"><input type="hidden" name="action" value="createAppointment">
 <div class="form-group"><label class="required">Bệnh nhân</label><select class="form-control" name="patientId" required><option value="">Chọn bệnh nhân</option><c:forEach var="p" items="${patients}"><option value="${p.patientId}"><c:out value="${p.fullName}"/> — <c:out value="${p.phone}"/></option></c:forEach></select></div>
 <div class="form-group"><label class="required">Bác sĩ</label><select class="form-control" name="doctorId" required><option value="">Chọn bác sĩ</option><c:forEach var="d" items="${doctors}"><option value="${d.doctorId}"><c:out value="${d.fullName}"/> — <c:out value="${d.specialty}"/></option></c:forEach></select></div>
 <div class="form-group"><label class="required">Thời gian</label><input class="form-control" type="datetime-local" name="appointmentAt" required></div><div class="form-group"><label class="required">Lý do khám</label><input class="form-control" name="reason" maxlength="255" required></div><div class="form-group"><label>Ghi chú</label><input class="form-control" name="note" maxlength="500"></div><div><button class="btn btn-primary">Đặt lịch</button></div></form></section></c:if>
 <section class="card"><div class="card-title">Danh sách lịch hẹn</div><div class="table-scroll"><table><thead><tr><th>Thời gian</th><th>Bệnh nhân</th><th>Bác sĩ</th><th>Lý do</th><th>Trạng thái</th><th></th></tr></thead><tbody><c:forEach var="a" items="${appointments}"><tr><td>${a.appointment_at}</td><td><strong><c:out value="${a.patient_name}"/></strong><br><small>${a.patient_phone}</small></td><td><c:out value="${a.doctor_name}"/></td><td><c:out value="${a.reason}"/></td><td><span class="status-pill status-${a.status}">${a.status}</span></td><td><c:if test="${a.status!='CHECKED_IN'&&(sessionScope.user.role=='STAFF'||sessionScope.user.role=='ADMIN')}"><form method="post" action="ClinicWorkflow" class="inline-form"><input type="hidden" name="action" value="checkIn"><input type="hidden" name="appointmentId" value="${a.appointment_id}"><button class="btn btn-success btn-sm">Check-in</button></form></c:if></td></tr></c:forEach></tbody></table></div></section>
</c:if>

<c:if test="${view=='encounters'}"><section class="card"><div class="card-title">Lượt khám và hàng đợi</div><div class="table-scroll"><table><thead><tr><th>STT</th><th>Bệnh nhân</th><th>Bác sĩ</th><th>Trạng thái</th><th>Hồ sơ</th><th></th></tr></thead><tbody><c:forEach var="e" items="${encounters}"><tr><td><span class="queue-number">${e.queue_number}</span></td><td><strong><c:out value="${e.patient_name}"/></strong><br><small>${e.patient_phone}</small></td><td><c:out value="${e.doctor_name}"/></td><td><span class="status-pill status-${e.status}">${e.status}</span></td><td><c:choose><c:when test="${empty e.record_id}"><c:if test="${sessionScope.user.role=='STAFF'}"><a class="btn btn-primary btn-sm" href="MedicalRecordForm?patientId=${e.patient_id}&encounterId=${e.encounter_id}">Nhập sinh hiệu</a></c:if></c:when><c:otherwise><a class="btn btn-outline-dark btn-sm" href="MedicalRecordForm?recordId=${e.record_id}&tab=4">Mở bệnh án</a></c:otherwise></c:choose></td><td><c:if test="${sessionScope.user.role=='DOCTOR'}"><form method="post" action="ClinicWorkflow" class="inline-form"><input type="hidden" name="action" value="status"><input type="hidden" name="encounterId" value="${e.encounter_id}"><input type="hidden" name="status" value="IN_CONSULTATION"><button class="btn btn-warning btn-sm">Bắt đầu khám</button></form></c:if></td></tr></c:forEach></tbody></table></div></section></c:if>

<c:if test="${view=='clinical'}"><section class="card"><div class="card-title">Chọn bệnh nhân</div><form method="get" class="search-bar"><input type="hidden" name="view" value="clinical"><select class="form-control" name="patientId" required><option value="">Chọn bệnh nhân</option><c:forEach var="p" items="${patients}"><option value="${p.patientId}" ${selectedPatient.patientId==p.patientId?'selected':''}><c:out value="${p.fullName}"/> — ${p.phone}</option></c:forEach></select><button class="btn btn-primary">Mở hồ sơ</button></form></section>
<c:if test="${not empty selectedPatient}"><div class="two-column"><section class="card"><div class="card-title">Dị ứng</div><c:forEach var="a" items="${allergies}"><div class="clinical-item"><strong><c:out value="${a.allergen}"/></strong><span>${a.severity}</span><p><c:out value="${a.reaction}"/></p></div></c:forEach><form method="post" action="ClinicWorkflow" class="compact-form"><input type="hidden" name="action" value="allergy"><input type="hidden" name="patientId" value="${selectedPatient.patientId}"><input class="form-control" name="allergen" placeholder="Tác nhân dị ứng" required><input class="form-control" name="reaction" placeholder="Phản ứng"><select class="form-control" name="severity"><option>UNKNOWN</option><option>MILD</option><option>MODERATE</option><option>SEVERE</option></select><button class="btn btn-primary">Lưu dị ứng</button></form></section>
<section class="card"><div class="card-title">Tiền sử bệnh</div><c:forEach var="h" items="${histories}"><div class="clinical-item"><strong><c:out value="${h.condition_name}"/></strong><span>${h.history_type}</span><p><c:out value="${h.note}"/></p></div></c:forEach><form method="post" action="ClinicWorkflow" class="compact-form"><input type="hidden" name="action" value="history"><input type="hidden" name="patientId" value="${selectedPatient.patientId}"><select class="form-control" name="historyType"><option>PERSONAL</option><option>FAMILY</option><option>SURGICAL</option><option>LIFESTYLE</option></select><input class="form-control" name="conditionName" placeholder="Tên bệnh/tình trạng" required><input class="form-control" type="date" name="diagnosedDate"><select class="form-control" name="historyStatus"><option>ACTIVE</option><option>RESOLVED</option></select><textarea class="form-control" name="historyNote" placeholder="Ghi chú"></textarea><button class="btn btn-primary">Lưu tiền sử</button></form></section></div></c:if></c:if>

<c:if test="${view=='labs'}">
<c:if test="${sessionScope.user.role=='DOCTOR'}"><section class="card"><div class="card-title">Tạo chỉ định xét nghiệm</div><form method="post" action="ClinicWorkflow" class="form-grid"><input type="hidden" name="action" value="labOrder">
<div class="form-group"><label class="required">Lượt khám</label><select class="form-control" name="encounterId" required><option value="">Chọn lượt khám đang phụ trách</option><c:forEach var="e" items="${encounters}"><c:if test="${e.status!='COMPLETED'&&e.status!='CANCELLED'}"><option value="${e.encounter_id}">#${e.queue_number} — <c:out value="${e.patient_name}"/></option></c:if></c:forEach></select></div>
<div class="form-group"><label class="required">Mã xét nghiệm</label><select class="form-control" name="testCode" required><option value="GLU">GLU — Đường huyết</option><option value="HBA1C">HBA1C — HbA1c</option><option value="LIPID">LIPID — Bộ mỡ máu</option><option value="CRE">CRE — Creatinine</option><option value="UACR">UACR — Albumin/Creatinine niệu</option></select></div>
<div class="form-group"><label class="required">Tên xét nghiệm</label><input class="form-control" name="testName" maxlength="150" required></div><div class="form-group"><label>Ưu tiên</label><select class="form-control" name="priority"><option>ROUTINE</option><option>URGENT</option></select></div><div class="form-group"><label>Ghi chú lâm sàng</label><input class="form-control" name="clinicalNote" maxlength="500"></div><div><button class="btn btn-primary">Tạo chỉ định</button></div></form></section></c:if>
<section class="card"><div class="card-title">Chỉ định và kết quả xét nghiệm</div><div class="table-scroll"><table><thead><tr><th>Bệnh nhân</th><th>Xét nghiệm</th><th>Ưu tiên</th><th>Kết quả</th><th>Trạng thái</th><th></th></tr></thead><tbody><c:forEach var="l" items="${labOrders}"><tr><td><c:out value="${l.patient_name}"/></td><td><strong><c:out value="${l.test_code}"/></strong> — <c:out value="${l.test_name}"/></td><td>${l.priority}</td><td><c:out value="${l.result_value}"/> <c:out value="${l.result_unit}"/><br><small><c:out value="${l.reference_range}"/> ${l.result_flag}</small></td><td><span class="status-pill">${l.status}</span></td><td><c:if test="${(sessionScope.user.role=='STAFF'||sessionScope.user.role=='ADMIN')&&l.status!='REVIEWED'&&l.status!='CANCELLED'}"><form method="post" action="ClinicWorkflow" class="result-form"><input type="hidden" name="action" value="labResult"><input type="hidden" name="labOrderId" value="${l.lab_order_id}"><input name="resultValue" placeholder="Kết quả" required><input name="resultUnit" placeholder="Đơn vị"><input name="referenceRange" placeholder="Tham chiếu"><select name="resultFlag"><option>NORMAL</option><option>LOW</option><option>HIGH</option><option>CRITICAL</option></select><button class="btn btn-success btn-sm">Trả kết quả</button></form></c:if></td></tr></c:forEach></tbody></table></div></section></c:if>
</main><jsp:include page="footer.jsp"/><script src="${pageContext.request.contextPath}/static/js/main.js"></script></body></html>
