<%@page contentType="text/html" pageEncoding="UTF-8"%><%@taglib prefix="c" uri="jakarta.tags.core"%>
<meta name="csrf-token" content="${sessionScope.csrfToken}">
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Đăng nhập — DiaCare Clinic</title><link rel="stylesheet" href="${pageContext.request.contextPath}/static/css/style.css"></head>
<body class="auth-body"><main class="auth-shell"><section class="auth-visual"><a class="auth-brand" href="${pageContext.request.contextPath}/"><span>+</span><div><strong>DiaCare Clinic</strong><small>Chăm sóc tiểu đường toàn diện</small></div></a><div class="auth-copy"><div class="auth-label">HỒ SƠ SỨC KHỎE ĐIỆN TỬ</div><h1>Mỗi dữ liệu đúng chỗ.<br>Mỗi quyết định đúng lúc.</h1><p>Nền tảng kết nối tiếp nhận, bác sĩ, xét nghiệm và người bệnh trong một quy trình ngoại trú liền mạch.</p><ul><li><span>✓</span> Hồ sơ tập trung và phân quyền an toàn</li><li><span>✓</span> Lịch hẹn, hàng đợi và lượt khám rõ ràng</li><li><span>✓</span> Kết quả xét nghiệm liên kết trực tiếp bệnh án</li></ul></div><div class="auth-support">Cần hỗ trợ? <strong>1800 1234</strong></div></section>
<section class="auth-panel"><div class="auth-form-wrap"><a class="auth-back" href="${pageContext.request.contextPath}/">← Về trang chủ</a><div class="auth-heading"><span class="auth-mobile-logo">+</span><h2>Chào mừng trở lại</h2><p>Đăng nhập để tiếp tục vào hệ thống DiaCare.</p></div>
<c:if test="${not empty requestScope.err}"><div class="alert alert-danger"><span>!</span><c:out value="${requestScope.err}"/></div></c:if>
<form action="${pageContext.request.contextPath}/Login" method="post" data-validate="login" class="auth-form"><div class="form-group"><label class="required" for="username">Tên đăng nhập</label><div class="input-with-icon"><span>👤</span><input id="username" type="text" name="username" class="form-control" value="${requestScope.username}" placeholder="Nhập tên đăng nhập" autocomplete="username" required autofocus></div></div><div class="form-group"><div class="label-row"><label class="required" for="password">Mật khẩu</label></div><div class="input-with-icon"><span>⌑</span><input id="password" type="password" name="password" class="form-control" placeholder="Nhập mật khẩu" autocomplete="current-password" required><button type="button" class="password-toggle" aria-label="Hiện mật khẩu" onclick="const p=document.getElementById('password');p.type=p.type==='password'?'text':'password';this.textContent=p.type==='password'?'Hiện':'Ẩn'">Hiện</button></div></div><c:if test="${not empty requestScope.lockUntil}"><div class="lock-message">Tài khoản tạm khóa. Thử lại sau <strong id="lock-timer"></strong>.</div></c:if><button type="submit" class="btn btn-primary auth-submit">Đăng nhập an toàn <span>→</span></button></form>
<div class="auth-note"><span>🔒</span><p>Phiên đăng nhập được bảo vệ và tự kết thúc sau 30 phút không hoạt động.</p></div></div><footer>© 2026 DiaCare Clinic</footer></section></main>
<script src="${pageContext.request.contextPath}/static/js/main.js"></script><script src="${pageContext.request.contextPath}/static/js/validate.js"></script>
<c:if test="${not empty requestScope.lockUntil}"><script>(function(){const lockUntil=${requestScope.lockUntil};const el=document.getElementById('lock-timer');const timer=setInterval(()=>{const left=lockUntil-Date.now();if(left<=0){clearInterval(timer);location.reload();return}el.textContent=Math.floor(left/60000)+' phút '+Math.floor(left/1000%60)+' giây'},1000)})();</script></c:if></body></html>
