package vn.diabetes.service;
import static org.junit.jupiter.api.Assertions.*;import java.time.*;import org.junit.jupiter.api.Test;
class ClinicWorkflowServiceTest {
 @Test void delegatesValidAppointment(){FakeGateway gateway=new FakeGateway();ClinicWorkflowService service=new ClinicWorkflowService(gateway,()->LocalDateTime.of(2026,7,16,8,0));service.createAppointment(1,2,LocalDateTime.of(2026,7,17,10,0),"Khám định kỳ","",9);assertTrue(gateway.created);}
 @Test void rejectsLongReasonBeforeGateway(){FakeGateway gateway=new FakeGateway();ClinicWorkflowService service=new ClinicWorkflowService(gateway,()->LocalDateTime.of(2026,7,16,8,0));assertThrows(IllegalArgumentException.class,()->service.createAppointment(1,2,LocalDateTime.of(2026,7,17,10,0),"x".repeat(256),"",9));assertFalse(gateway.created);}
 @Test void delegatesSimplePatientRequest(){FakeGateway gateway=new FakeGateway();ClinicWorkflowService service=new ClinicWorkflowService(gateway,()->LocalDateTime.of(2026,7,16,8,0));service.createAppointmentRequest(1,LocalDate.of(2026,7,17),"MORNING","Tái khám định kỳ","",9);assertTrue(gateway.requested);}
 @Test void rejectsInvalidWorkflowEnumsBeforeGateway(){FakeGateway gateway=new FakeGateway();ClinicWorkflowService service=new ClinicWorkflowService(gateway,()->LocalDateTime.of(2026,7,16,8,0));assertThrows(IllegalArgumentException.class,()->service.setEncounterStatus(1,"BROKEN",9));assertThrows(IllegalArgumentException.class,()->service.addAllergy(1,"Penicillin","Nổi ban","EXTREME",9));assertThrows(IllegalArgumentException.class,()->service.addHistory(1,"OTHER","Bệnh",null,"ACTIVE","",9));}
 @Test void rejectsFutureMedicalHistoryDate(){FakeGateway gateway=new FakeGateway();ClinicWorkflowService service=new ClinicWorkflowService(gateway,()->LocalDateTime.of(2026,7,16,8,0));assertThrows(IllegalArgumentException.class,()->service.addHistory(1,"PERSONAL","Tăng huyết áp",java.sql.Date.valueOf("2026-07-17"),"ACTIVE","",9));}
 private static class FakeGateway implements ClinicWorkflowGateway{boolean created;boolean requested;public void createAppointmentRequest(int p,LocalDate d,String period,String r,String n,int actor){requested=true;}public void assignAppointmentRequest(int i,int d,LocalDateTime a,String n,int actor){}public void createAppointment(int p,int d,LocalDateTime a,String r,String n,int actor){created=true;}public void rescheduleAppointment(int i,LocalDateTime a,String n,int actor){}public void setAppointmentStatus(int i,String s,int a){}public void cancelOwnAppointment(int i,int p,int a){}public void checkIn(int i,int a){}public void setEncounterStatus(int i,String s,int a){}public void addAllergy(int p,String al,String r,String s,int a){}public void addHistory(int p,String t,String n,java.sql.Date d,String s,String no,int a){}public void createLabOrder(int e,int d,String c,String n,String p,String no,int a){}public void resultLab(int o,String v,String u,String r,String f,int a){}}
}
