CREATE TABLE IF NOT EXISTS patient_ai_daily_advice (
  advice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id) ON DELETE CASCADE,
  advice_date DATE NOT NULL DEFAULT CURRENT_DATE,
  summary TEXT NOT NULL,
  advice_items_json TEXT NOT NULL,
  severity VARCHAR(10) NOT NULL CHECK (severity IN ('low','medium','high')),
  doctor_recommendation BOOLEAN NOT NULL DEFAULT FALSE,
  source_hash VARCHAR(64) NOT NULL,
  model VARCHAR(80) NOT NULL,
  fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_patient_ai_advice_day UNIQUE(patient_id, advice_date)
);

CREATE INDEX IF NOT EXISTS ix_patient_ai_advice_patient_date
  ON patient_ai_daily_advice(patient_id, advice_date DESC);
