CREATE TABLE IF NOT EXISTS login_history (
    login_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
    username VARCHAR(50),
    full_name VARCHAR(100),
    role VARCHAR(20),
    event_type VARCHAR(20) NOT NULL,
    ip_address VARCHAR(100),
    user_agent VARCHAR(500),
    session_id VARCHAR(120),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_login_history_event CHECK (event_type IN ('LOGIN','LOGOUT'))
);

CREATE INDEX IF NOT EXISTS ix_login_history_occurred_at
    ON login_history(occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_login_history_user
    ON login_history(user_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS admin_trash (
    trash_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(30) NOT NULL,
    entity_id INTEGER NOT NULL,
    display_name VARCHAR(150) NOT NULL,
    details TEXT,
    deleted_by INTEGER REFERENCES users(user_id),
    deleted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    restored_by INTEGER REFERENCES users(user_id),
    restored_at TIMESTAMPTZ,
    purged_by INTEGER REFERENCES users(user_id),
    purged_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_admin_trash_active
    ON admin_trash(deleted_at DESC)
    WHERE restored_at IS NULL AND purged_at IS NULL;
