CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
  full_name VARCHAR(100) NOT NULL, phone VARCHAR(15), role VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', email VARCHAR(100), dob DATE,
  gender VARCHAR(10), address VARCHAR(255), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cccd VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS doctors (
  doctor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(user_id), specialty VARCHAR(100) NOT NULL,
  license_no VARCHAR(50) NOT NULL UNIQUE, license_issue_date DATE, license_expire_date DATE,
  license_issued_by VARCHAR(150), degree VARCHAR(50), consultation_fee NUMERIC(18,2),
  face_image_path VARCHAR(255), cccd_image_path VARCHAR(255), license_image_path VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS patients (
  patient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER UNIQUE REFERENCES users(user_id), full_name VARCHAR(100) NOT NULL,
  date_of_birth DATE, gender VARCHAR(10), phone VARCHAR(15), address VARCHAR(255),
  health_insurance_no VARCHAR(20), created_by INTEGER, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  national_id VARCHAR(20), national_id_date DATE, national_id_place VARCHAR(150)
);
CREATE TABLE IF NOT EXISTS medicalrecords (
  record_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id), doctor_id INTEGER REFERENCES doctors(doctor_id),
  created_by_staff INTEGER, visit_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reason_for_visit VARCHAR(255), symptoms TEXT, medical_history TEXT, lifestyle_habits TEXT,
  clinical_exam TEXT, complication_note TEXT, final_diagnosis VARCHAR(255), treatment_plan TEXT,
  prescription_note TEXT, advice TEXT, follow_up_date DATE, doctor_note TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS healthindicators (
  indicator_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id INTEGER NOT NULL REFERENCES medicalrecords(record_id), entered_by_staff INTEGER,
  height NUMERIC(5,2), weight NUMERIC(5,2), bmi NUMERIC(4,2), systolic_bp INTEGER,
  diastolic_bp INTEGER, heart_rate INTEGER, temperature NUMERIC(4,1), blood_glucose NUMERIC(5,2),
  hba1c NUMERIC(4,2), cholesterol NUMERIC(5,2), triglyceride NUMERIC(5,2),
  hdl_c NUMERIC(5,2), ldl_c NUMERIC(5,2), measured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS aiwarnings (
  warning_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id INTEGER NOT NULL REFERENCES medicalrecords(record_id), risk_level VARCHAR(20),
  warning_message TEXT, suggested_action TEXT, ai_score NUMERIC(5,2),
  generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, reviewed_by_doctor BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS aiadvicehistory (
  advice_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id), advice_date DATE NOT NULL DEFAULT CURRENT_DATE,
  advice_content TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, risk_level VARCHAR(20),
  recommendation_type VARCHAR(50), source_data_reference TEXT, avg_glucose_7d NUMERIC(5,2), avg_systolic_7d INTEGER
);
CREATE TABLE IF NOT EXISTS patientdailylogs (
  log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id), log_date DATE NOT NULL DEFAULT CURRENT_DATE,
  blood_glucose NUMERIC(5,2), systolic_bp INTEGER, diastolic_bp INTEGER, weight NUMERIC(5,2),
  note TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, symptoms TEXT,
  heart_rate INTEGER, spo2 NUMERIC(4,1), meal_type VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS devicereadings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id), device_type VARCHAR(50) NOT NULL,
  raw_json_data TEXT NOT NULL, parsed_glucose NUMERIC(6,2), parsed_heart_rate INTEGER,
  parsed_systolic_bp INTEGER, parsed_diastolic_bp INTEGER, parsed_weight NUMERIC(5,2), parsed_spo2 NUMERIC(4,1),
  measured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_abnormal BOOLEAN NOT NULL DEFAULT FALSE, abnormal_note VARCHAR(500)
);
CREATE TABLE IF NOT EXISTS healthalerts (
  alert_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id), indicator_type VARCHAR(50) NOT NULL,
  value NUMERIC(8,2) NOT NULL, threshold NUMERIC(8,2) NOT NULL, alert_level VARCHAR(20) NOT NULL DEFAULT 'medium',
  alert_message VARCHAR(500) NOT NULL, data_source VARCHAR(20) NOT NULL DEFAULT 'manual', source_record_id INTEGER,
  is_acknowledged BOOLEAN NOT NULL DEFAULT FALSE, acknowledged_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS nextappointment (
  appointment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id), appointment_date DATE NOT NULL,
  source VARCHAR(20) NOT NULL DEFAULT 'AUTO', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_patients_created ON patients(created_at DESC);
CREATE INDEX IF NOT EXISTS ix_records_patient ON medicalrecords(patient_id, visit_date DESC);
CREATE INDEX IF NOT EXISTS ix_records_doctor_status ON medicalrecords(doctor_id, status, visit_date DESC);
CREATE INDEX IF NOT EXISTS ix_daily_patient_date ON patientdailylogs(patient_id, log_date DESC);
CREATE INDEX IF NOT EXISTS ix_device_patient_date ON devicereadings(patient_id, measured_at DESC);
CREATE INDEX IF NOT EXISTS ix_alert_patient_ack ON healthalerts(patient_id, is_acknowledged, created_at DESC);
