CREATE TABLE appointments (
  appointment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id),
  doctor_id INTEGER NOT NULL REFERENCES doctors(doctor_id),
  appointment_at TIMESTAMPTZ NOT NULL,
  reason VARCHAR(255) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'BOOKED',
  note VARCHAR(500), created_by INTEGER REFERENCES users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_appointment_status CHECK (status IN ('BOOKED','CONFIRMED','CHECKED_IN','COMPLETED','CANCELLED','NO_SHOW'))
);

CREATE TABLE encounters (
  encounter_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id INTEGER UNIQUE REFERENCES appointments(appointment_id),
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id),
  doctor_id INTEGER NOT NULL REFERENCES doctors(doctor_id),
  status VARCHAR(30) NOT NULL DEFAULT 'WAITING_TRIAGE',
  check_in_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  triage_at TIMESTAMPTZ, consultation_started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ,
  room_no VARCHAR(30), created_by INTEGER REFERENCES users(user_id),
  CONSTRAINT ck_encounter_status CHECK (status IN ('WAITING_TRIAGE','WAITING_DOCTOR','IN_CONSULTATION','WAITING_LAB','LAB_COMPLETED','COMPLETED','CANCELLED'))
);

CREATE TABLE queue_entries (
  queue_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  encounter_id INTEGER NOT NULL UNIQUE REFERENCES encounters(encounter_id),
  doctor_id INTEGER NOT NULL REFERENCES doctors(doctor_id),
  queue_number INTEGER NOT NULL, priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
  status VARCHAR(20) NOT NULL DEFAULT 'WAITING',
  queued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, called_at TIMESTAMPTZ,
  CONSTRAINT ck_queue_priority CHECK (priority IN ('NORMAL','PRIORITY','EMERGENCY')),
  CONSTRAINT ck_queue_status CHECK (status IN ('WAITING','CALLED','IN_SERVICE','COMPLETED','SKIPPED'))
);

CREATE TABLE patient_allergies (
  allergy_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id),
  allergen VARCHAR(150) NOT NULL, reaction VARCHAR(255), severity VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', noted_by INTEGER REFERENCES users(user_id),
  noted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_allergy_severity CHECK (severity IN ('MILD','MODERATE','SEVERE','UNKNOWN')),
  CONSTRAINT uq_patient_allergen UNIQUE(patient_id, allergen)
);

CREATE TABLE patient_medical_histories (
  history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id),
  history_type VARCHAR(30) NOT NULL, condition_name VARCHAR(150) NOT NULL,
  diagnosed_date DATE, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', note VARCHAR(500),
  noted_by INTEGER REFERENCES users(user_id), noted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_history_type CHECK (history_type IN ('PERSONAL','FAMILY','SURGICAL','LIFESTYLE'))
);

CREATE TABLE lab_orders (
  lab_order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  encounter_id INTEGER NOT NULL REFERENCES encounters(encounter_id),
  patient_id INTEGER NOT NULL REFERENCES patients(patient_id),
  doctor_id INTEGER NOT NULL REFERENCES doctors(doctor_id),
  test_code VARCHAR(30) NOT NULL, test_name VARCHAR(150) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ORDERED', priority VARCHAR(20) NOT NULL DEFAULT 'ROUTINE',
  clinical_note VARCHAR(500), ordered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  result_value VARCHAR(100), result_unit VARCHAR(30), reference_range VARCHAR(100), result_flag VARCHAR(20),
  resulted_by INTEGER REFERENCES users(user_id), resulted_at TIMESTAMPTZ,
  CONSTRAINT ck_lab_status CHECK (status IN ('ORDERED','COLLECTED','RESULTED','REVIEWED','CANCELLED')),
  CONSTRAINT ck_lab_priority CHECK (priority IN ('ROUTINE','URGENT'))
);

ALTER TABLE medicalrecords ADD COLUMN encounter_id INTEGER UNIQUE REFERENCES encounters(encounter_id);

CREATE TABLE audit_logs (
  audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(user_id), action VARCHAR(50) NOT NULL,
  entity_type VARCHAR(50) NOT NULL, entity_id VARCHAR(50), details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_appointments_date ON appointments(appointment_at, status);
CREATE UNIQUE INDEX uq_doctor_appointment_slot ON appointments(doctor_id, appointment_at)
  WHERE status IN ('BOOKED','CONFIRMED','CHECKED_IN');
CREATE INDEX ix_encounters_status ON encounters(status, check_in_at);
CREATE INDEX ix_queue_doctor ON queue_entries(doctor_id, status, queue_number);
CREATE INDEX ix_allergies_patient ON patient_allergies(patient_id, status);
CREATE INDEX ix_history_patient ON patient_medical_histories(patient_id, history_type);
CREATE INDEX ix_lab_encounter ON lab_orders(encounter_id, status);
CREATE UNIQUE INDEX uq_healthindicator_record ON healthindicators(record_id);
CREATE UNIQUE INDEX uq_dailylog_patient_date ON patientdailylogs(patient_id, log_date);
CREATE UNIQUE INDEX uq_users_cccd ON users(cccd) WHERE cccd IS NOT NULL AND cccd <> '';
CREATE UNIQUE INDEX uq_patients_national_id ON patients(national_id) WHERE national_id IS NOT NULL AND national_id <> '';
