CREATE TABLE IF NOT EXISTS PrescriptionItems (
    prescription_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id INTEGER NOT NULL REFERENCES MedicalRecords(record_id) ON DELETE CASCADE,
    medicine_name VARCHAR(150) NOT NULL,
    dosage VARCHAR(100) NOT NULL,
    frequency VARCHAR(100),
    duration_days INTEGER CHECK (duration_days BETWEEN 1 AND 365)
);

CREATE INDEX IF NOT EXISTS idx_prescription_record ON PrescriptionItems(record_id);

DROP TABLE IF EXISTS AIWarnings;
DROP TABLE IF EXISTS AIAdviceHistory;
